# Vendored from brunovicco/engineering-loop-schemas
# Version: 0.1.2
# Commit: 0459d61b7b1d4e7b46709e6d3895770553e6fab0
# Generated by scripts/render_vendor_bundle.py; do not edit by hand.
# Phase 0-1 remains report-only: this bundle validates contracts only.
"""Vendored validators for Evidence-Gated Engineering Loop contracts."""
